class RetryableError(Exception):
    pass

class ValidationError(Exception):
    pass

class InternalError(Exception):
    pass
